#pragma once

/*
 * Enum for all possible OnHitPassive IDs.
*/

enum OnHitPassive {
    ON_HIT_SARCOPHAGUS=0,
    ON_HIT_SHADE=1,
    ON_HIT_WISP=2,
    ON_HIT_IMP=3,
    ON_HIT_GRAVE=4,
    ON_HIT_CHEST=5,
    ON_HIT_ZOMBIE=6,
    ON_HIT_QUARTZ=7,
    ON_HIT_INEVITABLE=8,
    ON_HIT_FOUNTAIN=9,
    ON_HIT_WIZZ=10,
    ON_HIT_SLIMER=11,
    ON_HIT_OGRE=12,
    ON_HIT_DEMON=13,
    ON_HIT_CHOMP=14,
    ON_HIT_GHOST=15,
    ON_HIT_BOAR=16,
    ON_HIT_SPIKER=17,
    ON_HIT_SLATE=18,
    ON_HIT_CAW=19,
    ON_HIT_MAGRAT=20,
    ON_HIT_GYTHA=21,
    ON_HIT_AGNES=22,
    ON_HIT_BASILISK=23,
    ON_HIT_HYDRA=24,
    ON_HIT_CYCLOPS=25,
    ON_HIT_SLIME_QUEEN=26,
    ON_HIT_LICH=27,
    ON_HIT_BASALT=28,
    ON_HIT_TARANTUS=29,
    ON_HIT_HEXIA=30,
    ON_HIT_BARON=31,
    ON_HIT_THORN=32,
    ON_HIT_NO_PASSIVE=33
};