#pragma once
#include <map>
#include <string>
#include "env/entIDs.h"
#include "env/spellIDs.h"
#include "env/actions.h"
#include "env/ents.h"
#include "env/state.h"

inline const std::map<SideType, std::string> sidesReversedIDs = {
    {SideType::DAMAGE, "DAMAGE"},
    {SideType::SHIELD, "SHIELD"},
    {SideType::HEAL, "HEAL"},
    {SideType::HEALSHIELD, "HEALSHIELD"},
    {SideType::MANA, "MANA"},
    {SideType::BLANK, "BLANK"},
    {SideType::REROLL, "REROLL"},
    {SideType::REDIRECTINCOMING, "REDIRECTINCOMING"},
    {SideType::SUMMON, "SUMMON"},
    {SideType::RECHARGE, "RECHARGE"},
    {SideType::RESURRECT, "RESURRECT"},
    {SideType::ENCHANT, "ENCHANT"},
    {SideType::KILL, "KILL"},
    {SideType::UNDYING, "UNDYING"},
    {SideType::DODGE, "DODGE"},
    {SideType::SELF_DAMAGE, "SELF_DAMAGE"},
    {SideType::DAMAGE_ALL, "DAMAGE_ALL"},
    {SideType::DAMAGE_EVERYONE, "DAMAGE_EVERYONE"},
    {SideType::DAMAGE_FLANKING, "DAMAGE_FLANKING"},
    {SideType::SHIELD_ALL, "SHIELD_ALL"},
    {SideType::HEAL_ALL, "HEAL_ALL"},
    {SideType::STUN, "STUN"},
    {SideType::ERROR, "ERROR"}
};

inline const std::map<StateType, std::string> stateTypesReversedIDs = {
    {StateType::BATTLE, "BATTLE"},
    {StateType::EMPTY_FIGHT, "EMPTY_FIGHT"},
    {StateType::EMPTY_TURN, "EMPTY_TURN"},
    {StateType::EMPTY_REROLL, "EMPTY_REROLL"},
    {StateType::HERO_SELECT, "HERO_SELECT"},
    {StateType::LOST, "LOST"},
    {StateType::WON, "WON"}
};

inline const std::map<int, std::string> entsReversedIDs = {
    {THIEF, "THIEF"},
    {SCOUNDREL, "SCOUNDREL"},
    {LOST, "LOST"},
    {DABBLE, "DABBLE"},
    {CLUMSY, "CLUMSY"},
    {DABBLER, "DABBLER"},
    {GAMBLER, "GAMBLER"},
    {RANGER, "RANGER"},
    {ROGUE, "ROGUE"},
    {TRAPPER, "TRAPPER"},
    {SPELLBLADE, "SPELLBLADE"},
    {NINJA, "NINJA"},
    {JUGGLER, "JUGGLER"},
    {LUDUS, "LUDUS"},
    {ASSASSIN, "ASSASSIN"},
    {DANCER, "DANCER"},
    {FENCER, "FENCER"},
    {SHARPSHOT, "SHARPSHOT"},
    {VENOM, "VENOM"},
    {ROULETTE, "ROULETTE"},
    {DABBLEST, "DABBLEST"},
    {AGENT, "AGENT"},
    {FIGHTER, "FIGHTER"},
    {BRIGAND, "BRIGAND"},
    {LAZY, "LAZY"},
    {RUFFIAN, "RUFFIAN"},
    {HOARDER, "HOARDER"},
    {BERSERKER, "BERSERKER"},
    {BRUTE, "BRUTE"},
    {COLLECTOR, "COLLECTOR"},
    {GLADIATOR, "GLADIATOR"},
    {SOLDIER, "SOLDIER"},
    {WHIRL, "WHIRL"},
    {SCRAPPER, "SCRAPPER"},
    {SINEW, "SINEW"},
    {BARBARIAN, "BARBARIAN"},
    {BRAWLER, "BRAWLER"},
    {CURATOR, "CURATOR"},
    {LEADER, "LEADER"},
    {VETERAN, "VETERAN"},
    {BASH, "BASH"},
    {ECCENTRIC, "ECCENTRIC"},
    {CAPTAIN, "CAPTAIN"},
    {WANDERER, "WANDERER"},
    {DEFENDER, "DEFENDER"},
    {BUCKLE, "BUCKLE"},
    {SQUIRE, "SQUIRE"},
    {ALLOY, "ALLOY"},
    {WALLOP, "WALLOP"},
    {KNIGHT, "KNIGHT"},
    {ARMORER, "ARMORER"},
    {BARD, "BARD"},
    {CLERIC, "CLERIC"},
    {GUARDIAN, "GUARDIAN"},
    {PILGRIM, "PILGRIM"},
    {MONK, "MONK"},
    {WARDEN, "WARDEN"},
    {KEEPER, "KEEPER"},
    {PALADIN, "PALADIN"},
    {PRINCE, "PRINCE"},
    {STALWART, "STALWART"},
    {POET, "POET"},
    {VALKYRIE, "VALKYRIE"},
    {STOIC, "STOIC"},
    {HEALER, "HEALER"},
    {GARDENER, "GARDENER"},
    {ACOLYTE, "ACOLYTE"},
    {MYSTIC, "MYSTIC"},
    {SPLINT, "SPLINT"},
    {DRUID, "DRUID"},
    {HERBALIST, "HERBALIST"},
    {MEDIC, "MEDIC"},
    {PRIESTESS, "PRIESTESS"},
    {VAMPIRE, "VAMPIRE"},
    {ENCHANTER, "ENCHANTER"},
    {DISCIPLE, "DISCIPLE"},
    {FEY, "FEY"},
    {DOCTOR, "DOCTOR"},
    {FORSAKEN, "FORSAKEN"},
    {PROPHET, "PROPHET"},
    {SHAMAN, "SHAMAN"},
    {WITCH, "WITCH"},
    {WRAITH, "WRAITH"},
    {SURGEON, "SURGEON"},
    {FATE, "FATE"},
    {MAGE, "MAGE"},
    {PRODIGY, "PRODIGY"},
    {MEDDLER, "MEDDLER"},
    {STUDENT, "STUDENT"},
    {INITIATE, "INITIATE"},
    {CULTIST, "CULTIST"},
    {CALDERA, "CALDERA"},
    {EVOKER, "EVOKER"},
    {GLACIA, "GLACIA"},
    {JESTER, "JESTER"},
    {SPARKY, "SPARKY"},
    {MYCO, "MYCO"},
    {SEER, "SEER"},
    {FIEND, "FIEND"},
    {ARTIFICER, "ARTIFICER"},
    {WEAVER, "WEAVER"},
    {SORCERER, "SORCERER"},
    {CHRONOS, "CHRONOS"},
    {WARLOCK, "WARLOCK"},
    {ACE, "ACE"},
    {GHAST, "GHAST"},
    {WIZARD, "WIZARD"},
    {SLIMELET, "SLIMELET"},
    {IMP, "IMP"},
    {WOLF, "WOLF"},
    {SPIDER, "SPIDER"},
    {SLIMER, "SLIMER"},
    {SABER, "SABER"},
    {SLATE, "SLATE"},
    {DRAGON, "DRAGON"},
    {CAW, "CAW"},
    {DEMON, "DEMON"},
    {THORN, "THORN"},
    {BONES, "BONES"},
    {SHADE, "SHADE"},
    {RAT, "RAT"},
    {WISP, "WISP"},
    {BEE, "BEE"},
    {GRAVE, "GRAVE"},
    {ILLUSION, "ILLUSION"},
    {CHEST, "CHEST"},
    {ARCHER, "ARCHER"},
    {GOBLIN, "GOBLIN"},
    {GNOLL, "GNOLL"},
    {ZOMBIE, "ZOMBIE"},
    {SEED, "SEED"},
    {SNAKE, "SNAKE"},
    {QUARTZ, "QUARTZ"},
    {SUDUL, "SUDUL"},
    {FANATIC, "FANATIC"},
    {MILITIA, "MILITIA"},
    {CARRIER, "CARRIER"},
    {BANDIT, "BANDIT"},
    {BARREL, "BARREL"},
    {GOLEM, "GOLEM"},
    {FOUNTAIN, "FOUNTAIN"},
    {WARCHIEF, "WARCHIEF"},
    {BLIND, "BLIND"},
    {WIZZ, "WIZZ"},
    {ALPHA, "ALPHA"},
    {OGRE, "OGRE"},
    {LOG, "LOG"},
    {CHOMP, "CHOMP"},
    {GHOST, "GHOST"},
    {BOAR, "BOAR"},
    {SPIKER, "SPIKER"},
    {SLIME_QUEEN, "SLIME_QUEEN"},
    {LICH, "LICH"},
    {TROLL_KING, "TROLL_KING"},
    {BASALT, "BASALT"},
    {TARANTUS, "TARANTUS"},
    {ROTTEN, "ROTTEN"},
    {HEXIA, "HEXIA"},
    {BARON, "BARON"},
    {SARCOPHAGUS, "SARCOPHAGUS"},
    {BELL, "BELL"},
    {MADNESS, "MADNESS"},
    {INEVITABLE, "INEVITABLE"},
    {THE_HAND, "THE_HAND"},
    {TROLL, "TROLL"},
    {MAGRAT, "MAGRAT"},
    {GYTHA, "GYTHA"},
    {AGNES, "AGNES"},
    {BASILISK, "BASILISK"},
    {HYDRA, "HYDRA"},
    {CYCLOPS, "CYCLOPS"},
    {BRAMBLE, "BRAMBLE"},
    {BANSHEE, "BANSHEE"},
    {DRAGON_EGG, "DRAGON_EGG"},
    {CAW_EGG, "CAW_EGG"},
    {SNIPER, "SNIPER"}
};

inline const std::map<int, std::string> spellsReversedIDs = {
    {MEND, "MEND"},
    {HEMLOCK, "HEMLOCK"},
    {RESTORE, "RESTORE"},
    {GAZE, "GAZE"},
    {BANDAGE, "BANDAGE"},
    {BALANCE, "BALANCE"},
    {VINE, "VINE"},
    {RENEW, "RENEW"},
    {PRAY, "PRAY"},
    {INFUSE, "INFUSE"},
    {FLIP, "FLIP"},
    {GLOW, "GLOW"},
    {CIRCLE, "CIRCLE"},
    {LIQUOR, "LIQUOR"},
    {BIND, "BIND"},
    {SOOTHE, "SOOTHE"},
    {RITUAL, "RITUAL"},
    {SALVE, "SALVE"},
    {LEECH, "LEECH"},
    {OPERATE, "OPERATE"},
    {STRAND, "STRAND"},
    {POKE, "POKE"},
    {SCORCH, "SCORCH"},
    {SLAY, "SLAY"},
    {SLICE, "SLICE"},
    {GATHER, "GATHER"},
    {CUT, "CUT"},
    {SCALD, "SCALD"},
    {DROP, "DROP"},
    {CHILL, "CHILL"},
    {FLICK, "FLICK"},
    {ZAP, "ZAP"},
    {SPORE, "SPORE"},
    {FORETELL, "FORETELL"},
    {BURN, "BURN"},
    {BLADES, "BLADES"},
    {CRUSH, "CRUSH"},
    {MIASMA, "MIASMA"},
    {TICK, "TICK"},
    {BLAZE, "BLAZE"},
    {DRAW, "DRAW"},
    {HARVEST, "HARVEST"},
    {INSPIRE, "INSPIRE"},
    {IMBUE, "IMBUE"},
    {FORMATION, "FORMATION"},
    {PARRY, "PARRY"},
    {ELSE, "ELSE"},
    {LIGHT, "LIGHT"},
    {UNITE, "UNITE"},
    {CLINK, "CLINK"},
    {BURST, "BURST"}
};

inline const std::map<std::pair<int,std::pair<int,int>>, int> actionsReversedIDs = {
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, -1)), 0},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 0)), 1},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 1)), 2},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 2)), 3},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 3)), 4},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 4)), 5},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 0)), 6},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 1)), 7},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 2)), 8},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 3)), 9},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 4)), 10},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 5)), 11},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 6)), 12},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 7)), 13},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 8)), 14},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 9)), 15},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, -1)), 16},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 0)), 17},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 1)), 18},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 2)), 19},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 3)), 20},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 4)), 21},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 0)), 22},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 1)), 23},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 2)), 24},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 3)), 25},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 4)), 26},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 5)), 27},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 6)), 28},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 7)), 29},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 8)), 30},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 9)), 31},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, -1)), 32},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 0)), 33},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 1)), 34},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 2)), 35},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 3)), 36},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 4)), 37},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 0)), 38},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 1)), 39},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 2)), 40},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 3)), 41},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 4)), 42},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 5)), 43},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 6)), 44},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 7)), 45},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 8)), 46},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 9)), 47},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, -1)), 48},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 0)), 49},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 1)), 50},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 2)), 51},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 3)), 52},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 4)), 53},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 0)), 54},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 1)), 55},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 2)), 56},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 3)), 57},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 4)), 58},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 5)), 59},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 6)), 60},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 7)), 61},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 8)), 62},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 9)), 63},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, -1)), 64},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 0)), 65},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 1)), 66},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 2)), 67},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 3)), 68},
    {std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 4)), 69},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 0)), 70},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 1)), 71},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 2)), 72},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 3)), 73},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 4)), 74},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 5)), 75},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 6)), 76},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 7)), 77},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 8)), 78},
    {std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 9)), 79},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 0)), 80},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 1)), 81},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 2)), 82},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 3)), 83},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 4)), 84},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 0)), 85},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 1)), 86},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 2)), 87},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 3)), 88},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 4)), 89},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 5)), 90},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 6)), 91},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 7)), 92},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 8)), 93},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 9)), 94},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 0)), 95},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 1)), 96},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 2)), 97},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 3)), 98},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 4)), 99},
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 0)), // imbue cannot affect enemy
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 1)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 2)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 3)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 4)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 5)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 6)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 7)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 8)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 9)),
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, -1)), 100}, // Formation is untargeted, so targetNum is -1
    //std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 0)),
    //std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 1)),
    //std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 2)),
    //std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 3)),
    //std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 4)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 0)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 1)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 2)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 3)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 4)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 5)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 6)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 7)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 8)),
    //std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 9)),
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, -1)), 101}, // For untargeted Gray spells
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 0)), 102},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 1)), 103},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 2)), 104},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 3)), 105},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 4)), 106},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 0)), 107},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 1)), 108},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 2)), 109},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 3)), 110},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 4)), 111},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 5)), 112},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 6)), 113},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 7)), 114},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 8)), 115},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 9)), 116},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, -1)), 117}, // For untargeted Red spells
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 0)), 118},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 1)), 119},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 2)), 120},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 3)), 121},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 4)), 122},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 0)), 123},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 1)), 124},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 2)), 125},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 3)), 126},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 4)), 127},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 5)), 128},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 6)), 129},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 7)), 130},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 8)), 131},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 9)), 132},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, -1)), 133}, // For untargeted Blue spells
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 0)), 134},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 1)), 135},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 2)), 136},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 3)), 137},
    {std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 4)), 138},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 0)), 139},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 1)), 140},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 2)), 141},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 3)), 142},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 4)), 143},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 5)), 144},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 6)), 145},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 7)), 146},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 8)), 147},
    {std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 9)), 148},
    {std::make_pair(REROLL_ACTION,std::make_pair(0,0)), 149}, // For skipping rerolls, since AI is forced to fully roll down
    {std::make_pair(REROLL_ACTION,std::make_pair(1,0)), 150},
    {std::make_pair(REROLL_ACTION,std::make_pair(2,0)), 151},
    {std::make_pair(REROLL_ACTION,std::make_pair(3,0)), 152},
    {std::make_pair(REROLL_ACTION,std::make_pair(4,0)), 153},
    {std::make_pair(REROLL_ACTION,std::make_pair(5,0)), 154},
    {std::make_pair(REROLL_ACTION,std::make_pair(6,0)), 155},
    {std::make_pair(REROLL_ACTION,std::make_pair(7,0)), 156},
    {std::make_pair(REROLL_ACTION,std::make_pair(8,0)), 157},
    {std::make_pair(REROLL_ACTION,std::make_pair(9,0)), 158},
    {std::make_pair(REROLL_ACTION,std::make_pair(10,0)), 159},
    {std::make_pair(REROLL_ACTION,std::make_pair(11,0)), 160},
    {std::make_pair(REROLL_ACTION,std::make_pair(12,0)), 161},
    {std::make_pair(REROLL_ACTION,std::make_pair(13,0)), 162},
    {std::make_pair(REROLL_ACTION,std::make_pair(14,0)), 163},
    {std::make_pair(REROLL_ACTION,std::make_pair(15,0)), 164},
    {std::make_pair(REROLL_ACTION,std::make_pair(16,0)), 165},
    {std::make_pair(REROLL_ACTION,std::make_pair(17,0)), 166},
    {std::make_pair(REROLL_ACTION,std::make_pair(18,0)), 167},
    {std::make_pair(REROLL_ACTION,std::make_pair(19,0)), 168},
    {std::make_pair(REROLL_ACTION,std::make_pair(20,0)), 169},
    {std::make_pair(REROLL_ACTION,std::make_pair(21,0)), 170},
    {std::make_pair(REROLL_ACTION,std::make_pair(22,0)), 171},
    {std::make_pair(REROLL_ACTION,std::make_pair(23,0)), 172},
    {std::make_pair(REROLL_ACTION,std::make_pair(24,0)), 173},
    {std::make_pair(REROLL_ACTION,std::make_pair(25,0)), 174},
    {std::make_pair(REROLL_ACTION,std::make_pair(26,0)), 175},
    {std::make_pair(REROLL_ACTION,std::make_pair(27,0)), 176},
    {std::make_pair(REROLL_ACTION,std::make_pair(28,0)), 177},
    {std::make_pair(REROLL_ACTION,std::make_pair(29,0)), 178},
    {std::make_pair(REROLL_ACTION,std::make_pair(30,0)), 179},
    {std::make_pair(REROLL_ACTION,std::make_pair(31,0)), 180},
    {std::make_pair(END_TURN_ACTION,std::make_pair(0,0)), 181},
    {std::make_pair(CONTINUE_ACTION,std::make_pair(0,0)), 182},
};

inline const std::map<int, std::string> keywordsReversedIDs = {
    {0, "RANGED"},
    {1, "HEAVY"},
    {2, "STICKY"},
    {3, "MANDATORY"},
    {4, "CANTRIP"},
    {5, "STASIS"},
    {6, "ELIMINATE"},
    // Copycat
    {7, "COPYCAT"},
    // Statics
    {8, "PRISTINE"},
    {9, "DEATHWISH"},
    {10, "CHAIN"},
    {11, "BLOODLUST"},
    {12, "STEEL"},
    {13, "CHARGED"},
    {14, "ERA"},
    {15, "INSPIRED"},
    {16, "DEFY"},
    {17, "PAIR"},
    {18, "TRIO"},
    {19, "PLAGUE"},
    // Selfshield must be before the action for spikymons, and must happen only once (not once per target). Selfheal must be after
    {20, "SELFSHIELD"}, // Selfshield is the only action in this category
    // Dynamic keywords
    {21, "FOCUS"},
    {22, "CRUEL"},
    {23, "ENGAGE"},
    // Effects applying once per target (selfshield, selfheal, etc. dont apply once per target, but also dont have cleave. Cleanse, poison, weaken, inflicts do though)
    {24, "POISON"},
    {25, "CLEANSE"},
    {26, "VITALITY"},
    {27, "REGEN"},
    {28, "INFLICT_PAIN"},
    {29, "INFLICT_EXERT"},
    {30, "INFLICT_DEATH"},
    {31, "INFLICT_SINGLEUSE"},
    {32, "PETRIFY"},
    {33, "GUILT"},
    {34, "WEAKEN"},
    {35, "VULNERABLE"},
    {36, "BOOST"},
    {37, "SMITH"},
    {38, "PERMABOOST"},
    // Action Time. These keywords are handled by useDice, instead of in the keyword function in keywords.py
    {39, "RAMPAGE"},
    {40, "RESCUE"},
    {41, "DOUBLEUSE"},
    {42, "QUADUSE"},
    {43, "CLEAVE"},
    {44, "DESCEND"},
    {45, "REPEL"},
    // BONED
    {46, "BONED"},
    // Post Attack Effects
    {47, "DEATH"},
    {48, "PAIN"},
    {49, "MANAGAIN"},
    {50, "SELFHEAL"},
    {51, "DUPLICATE"},
    {52, "EXERT"},
    {53, "GROOOOWTH"},
    {54, "GROWTH"},
    {55, "SINGLEUSE"},
    {56, "DECAY"},
};
