from bitarray import bitarray

"""
Action space is discrete, with some of the following actions being available per time step according to validActions.py
"""
DICE_ALLY_ACTION = 0
DICE_ENEMY_ACTION = 1
SPELL_ALLY_ACTION = 2
SPELL_ENEMY_ACTION = 3
REROLL_ACTION = 4
END_TURN_ACTION = 5
CONTINUE_ACTION = 6
ACTION_MAP = [
    (DICE_ALLY_ACTION,(0, -1)),
    (DICE_ALLY_ACTION,(0, 0)),
    (DICE_ALLY_ACTION,(0, 1)),
    (DICE_ALLY_ACTION,(0, 2)),
    (DICE_ALLY_ACTION,(0, 3)),
    (DICE_ALLY_ACTION,(0, 4)),
    (DICE_ENEMY_ACTION,(0, 0)),
    (DICE_ENEMY_ACTION,(0, 1)),
    (DICE_ENEMY_ACTION,(0, 2)),
    (DICE_ENEMY_ACTION,(0, 3)),
    (DICE_ENEMY_ACTION,(0, 4)),
    (DICE_ENEMY_ACTION,(0, 5)),
    (DICE_ENEMY_ACTION,(0, 6)),
    (DICE_ENEMY_ACTION,(0, 7)),
    (DICE_ENEMY_ACTION,(0, 8)),
    (DICE_ENEMY_ACTION,(0, 9)),
    (DICE_ALLY_ACTION,(1, -1)),
    (DICE_ALLY_ACTION,(1, 0)),
    (DICE_ALLY_ACTION,(1, 1)),
    (DICE_ALLY_ACTION,(1, 2)),
    (DICE_ALLY_ACTION,(1, 3)),
    (DICE_ALLY_ACTION,(1, 4)),
    (DICE_ENEMY_ACTION,(1, 0)),
    (DICE_ENEMY_ACTION,(1, 1)),
    (DICE_ENEMY_ACTION,(1, 2)),
    (DICE_ENEMY_ACTION,(1, 3)),
    (DICE_ENEMY_ACTION,(1, 4)),
    (DICE_ENEMY_ACTION,(1, 5)),
    (DICE_ENEMY_ACTION,(1, 6)),
    (DICE_ENEMY_ACTION,(1, 7)),
    (DICE_ENEMY_ACTION,(1, 8)),
    (DICE_ENEMY_ACTION,(1, 9)),
    (DICE_ALLY_ACTION,(2, -1)),
    (DICE_ALLY_ACTION,(2, 0)),
    (DICE_ALLY_ACTION,(2, 1)),
    (DICE_ALLY_ACTION,(2, 2)),
    (DICE_ALLY_ACTION,(2, 3)),
    (DICE_ALLY_ACTION,(2, 4)),
    (DICE_ENEMY_ACTION,(2, 0)),
    (DICE_ENEMY_ACTION,(2, 1)),
    (DICE_ENEMY_ACTION,(2, 2)),
    (DICE_ENEMY_ACTION,(2, 3)),
    (DICE_ENEMY_ACTION,(2, 4)),
    (DICE_ENEMY_ACTION,(2, 5)),
    (DICE_ENEMY_ACTION,(2, 6)),
    (DICE_ENEMY_ACTION,(2, 7)),
    (DICE_ENEMY_ACTION,(2, 8)),
    (DICE_ENEMY_ACTION,(2, 9)),
    (DICE_ALLY_ACTION,(3, -1)),
    (DICE_ALLY_ACTION,(3, 0)),
    (DICE_ALLY_ACTION,(3, 1)),
    (DICE_ALLY_ACTION,(3, 2)),
    (DICE_ALLY_ACTION,(3, 3)),
    (DICE_ALLY_ACTION,(3, 4)),
    (DICE_ENEMY_ACTION,(3, 0)),
    (DICE_ENEMY_ACTION,(3, 1)),
    (DICE_ENEMY_ACTION,(3, 2)),
    (DICE_ENEMY_ACTION,(3, 3)),
    (DICE_ENEMY_ACTION,(3, 4)),
    (DICE_ENEMY_ACTION,(3, 5)),
    (DICE_ENEMY_ACTION,(3, 6)),
    (DICE_ENEMY_ACTION,(3, 7)),
    (DICE_ENEMY_ACTION,(3, 8)),
    (DICE_ENEMY_ACTION,(3, 9)),
    (DICE_ALLY_ACTION,(4, -1)),
    (DICE_ALLY_ACTION,(4, 0)),
    (DICE_ALLY_ACTION,(4, 1)),
    (DICE_ALLY_ACTION,(4, 2)),
    (DICE_ALLY_ACTION,(4, 3)),
    (DICE_ALLY_ACTION,(4, 4)),
    (DICE_ENEMY_ACTION,(4, 0)),
    (DICE_ENEMY_ACTION,(4, 1)),
    (DICE_ENEMY_ACTION,(4, 2)),
    (DICE_ENEMY_ACTION,(4, 3)),
    (DICE_ENEMY_ACTION,(4, 4)),
    (DICE_ENEMY_ACTION,(4, 5)),
    (DICE_ENEMY_ACTION,(4, 6)),
    (DICE_ENEMY_ACTION,(4, 7)),
    (DICE_ENEMY_ACTION,(4, 8)),
    (DICE_ENEMY_ACTION,(4, 9)),
    (SPELL_ALLY_ACTION,(0, 0)),
    (SPELL_ALLY_ACTION,(0, 1)),
    (SPELL_ALLY_ACTION,(0, 2)),
    (SPELL_ALLY_ACTION,(0, 3)),
    (SPELL_ALLY_ACTION,(0, 4)),
    (SPELL_ENEMY_ACTION,(0, 0)),
    (SPELL_ENEMY_ACTION,(0, 1)),
    (SPELL_ENEMY_ACTION,(0, 2)),
    (SPELL_ENEMY_ACTION,(0, 3)),
    (SPELL_ENEMY_ACTION,(0, 4)),
    (SPELL_ENEMY_ACTION,(0, 5)),
    (SPELL_ENEMY_ACTION,(0, 6)),
    (SPELL_ENEMY_ACTION,(0, 7)),
    (SPELL_ENEMY_ACTION,(0, 8)),
    (SPELL_ENEMY_ACTION,(0, 9)),
    (SPELL_ALLY_ACTION,(1, 0)),
    (SPELL_ALLY_ACTION,(1, 1)),
    (SPELL_ALLY_ACTION,(1, 2)),
    (SPELL_ALLY_ACTION,(1, 3)),
    (SPELL_ALLY_ACTION,(1, 4)),
    # (SPELL_ENEMY_ACTION,(1, 0)), # imbue cannot affect enemy
    # (SPELL_ENEMY_ACTION,(1, 1)),
    # (SPELL_ENEMY_ACTION,(1, 2)),
    # (SPELL_ENEMY_ACTION,(1, 3)),
    # (SPELL_ENEMY_ACTION,(1, 4)),
    # (SPELL_ENEMY_ACTION,(1, 5)),
    # (SPELL_ENEMY_ACTION,(1, 6)),
    # (SPELL_ENEMY_ACTION,(1, 7)),
    # (SPELL_ENEMY_ACTION,(1, 8)),
    # (SPELL_ENEMY_ACTION,(1, 9)),
    (SPELL_ALLY_ACTION,(2, -1)), # Formation is untargeted, so targetNum is -1
    # (SPELL_ALLY_ACTION,(2, 0)),
    # (SPELL_ALLY_ACTION,(2, 1)),
    # (SPELL_ALLY_ACTION,(2, 2)),
    # (SPELL_ALLY_ACTION,(2, 3)),
    # (SPELL_ALLY_ACTION,(2, 4)),
    # (SPELL_ENEMY_ACTION,(2, 0)),
    # (SPELL_ENEMY_ACTION,(2, 1)),
    # (SPELL_ENEMY_ACTION,(2, 2)),
    # (SPELL_ENEMY_ACTION,(2, 3)),
    # (SPELL_ENEMY_ACTION,(2, 4)),
    # (SPELL_ENEMY_ACTION,(2, 5)),
    # (SPELL_ENEMY_ACTION,(2, 6)),
    # (SPELL_ENEMY_ACTION,(2, 7)),
    # (SPELL_ENEMY_ACTION,(2, 8)),
    # (SPELL_ENEMY_ACTION,(2, 9)),
    (SPELL_ALLY_ACTION,(3, -1)), # For untargeted Gray spells
    (SPELL_ALLY_ACTION,(3, 0)),
    (SPELL_ALLY_ACTION,(3, 1)),
    (SPELL_ALLY_ACTION,(3, 2)),
    (SPELL_ALLY_ACTION,(3, 3)),
    (SPELL_ALLY_ACTION,(3, 4)),
    (SPELL_ENEMY_ACTION,(3, 0)),
    (SPELL_ENEMY_ACTION,(3, 1)),
    (SPELL_ENEMY_ACTION,(3, 2)),
    (SPELL_ENEMY_ACTION,(3, 3)),
    (SPELL_ENEMY_ACTION,(3, 4)),
    (SPELL_ENEMY_ACTION,(3, 5)),
    (SPELL_ENEMY_ACTION,(3, 6)),
    (SPELL_ENEMY_ACTION,(3, 7)),
    (SPELL_ENEMY_ACTION,(3, 8)),
    (SPELL_ENEMY_ACTION,(3, 9)),
    (SPELL_ALLY_ACTION,(4, -1)), # For untargeted Red spells
    (SPELL_ALLY_ACTION,(4, 0)),
    (SPELL_ALLY_ACTION,(4, 1)),
    (SPELL_ALLY_ACTION,(4, 2)),
    (SPELL_ALLY_ACTION,(4, 3)),
    (SPELL_ALLY_ACTION,(4, 4)),
    (SPELL_ENEMY_ACTION,(4, 0)),
    (SPELL_ENEMY_ACTION,(4, 1)),
    (SPELL_ENEMY_ACTION,(4, 2)),
    (SPELL_ENEMY_ACTION,(4, 3)),
    (SPELL_ENEMY_ACTION,(4, 4)),
    (SPELL_ENEMY_ACTION,(4, 5)),
    (SPELL_ENEMY_ACTION,(4, 6)),
    (SPELL_ENEMY_ACTION,(4, 7)),
    (SPELL_ENEMY_ACTION,(4, 8)),
    (SPELL_ENEMY_ACTION,(4, 9)),
    (SPELL_ALLY_ACTION,(5, -1)), # For untargeted Blue spells
    (SPELL_ALLY_ACTION,(5, 0)),
    (SPELL_ALLY_ACTION,(5, 1)),
    (SPELL_ALLY_ACTION,(5, 2)),
    (SPELL_ALLY_ACTION,(5, 3)),
    (SPELL_ALLY_ACTION,(5, 4)),
    (SPELL_ENEMY_ACTION,(5, 0)),
    (SPELL_ENEMY_ACTION,(5, 1)),
    (SPELL_ENEMY_ACTION,(5, 2)),
    (SPELL_ENEMY_ACTION,(5, 3)),
    (SPELL_ENEMY_ACTION,(5, 4)),
    (SPELL_ENEMY_ACTION,(5, 5)),
    (SPELL_ENEMY_ACTION,(5, 6)),
    (SPELL_ENEMY_ACTION,(5, 7)),
    (SPELL_ENEMY_ACTION,(5, 8)),
    (SPELL_ENEMY_ACTION,(5, 9)),
    (REROLL_ACTION,bitarray('00000')), # For skipping rerolls, since AI is forced to fully roll down
    (REROLL_ACTION,bitarray('10000')),
    (REROLL_ACTION,bitarray('01000')),
    (REROLL_ACTION,bitarray('11000')),
    (REROLL_ACTION,bitarray('00100')),
    (REROLL_ACTION,bitarray('10100')),
    (REROLL_ACTION,bitarray('01100')),
    (REROLL_ACTION,bitarray('11100')),
    (REROLL_ACTION,bitarray('00010')),
    (REROLL_ACTION,bitarray('10010')),
    (REROLL_ACTION,bitarray('01010')),
    (REROLL_ACTION,bitarray('11010')),
    (REROLL_ACTION,bitarray('00110')),
    (REROLL_ACTION,bitarray('10110')),
    (REROLL_ACTION,bitarray('01110')),
    (REROLL_ACTION,bitarray('11110')),
    (REROLL_ACTION,bitarray('00001')),
    (REROLL_ACTION,bitarray('10001')),
    (REROLL_ACTION,bitarray('01001')),
    (REROLL_ACTION,bitarray('11001')),
    (REROLL_ACTION,bitarray('00101')),
    (REROLL_ACTION,bitarray('10101')),
    (REROLL_ACTION,bitarray('01101')),
    (REROLL_ACTION,bitarray('11101')),
    (REROLL_ACTION,bitarray('00011')),
    (REROLL_ACTION,bitarray('10011')),
    (REROLL_ACTION,bitarray('01011')),
    (REROLL_ACTION,bitarray('11011')),
    (REROLL_ACTION,bitarray('00111')),
    (REROLL_ACTION,bitarray('10111')),
    (REROLL_ACTION,bitarray('01111')),
    (REROLL_ACTION,bitarray('11111')),
    (END_TURN_ACTION,0),
    (CONTINUE_ACTION,0),
]