#pragma once
#include <vector>
#include <utility>

inline constexpr int DICE_ALLY_ACTION = 0;
inline constexpr int DICE_ENEMY_ACTION = 1;
inline constexpr int SPELL_ALLY_ACTION = 2;
inline constexpr int SPELL_ENEMY_ACTION = 3;
inline constexpr int REROLL_ACTION = 4;
inline constexpr int END_TURN_ACTION = 5;
inline constexpr int CONTINUE_ACTION = 6;
inline std::vector<std::pair<int, std::pair<int, int>>> ACTION_MAP = {
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, -1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 0)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 2)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 3)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(0, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 0)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 1)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 2)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 3)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 5)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 6)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 7)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 8)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(0, 9)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, -1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 0)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 2)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 3)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(1, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 0)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 1)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 2)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 3)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 5)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 6)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 7)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 8)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(1, 9)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, -1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 0)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 2)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 3)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(2, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 0)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 1)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 2)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 3)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 5)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 6)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 7)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 8)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(2, 9)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, -1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 0)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 2)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 3)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(3, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 0)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 1)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 2)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 3)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 5)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 6)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 7)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 8)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(3, 9)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, -1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 0)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 1)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 2)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 3)),
    std::make_pair(DICE_ALLY_ACTION,std::make_pair(4, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 0)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 1)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 2)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 3)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 4)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 5)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 6)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 7)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 8)),
    std::make_pair(DICE_ENEMY_ACTION,std::make_pair(4, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 0)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 1)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 2)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 3)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(0, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 0)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 1)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 2)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 3)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 5)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 6)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 7)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 8)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(0, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 0)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 1)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 2)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 3)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(1, 4)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 0)), // imbue cannot affect enemy
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 1)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 2)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 3)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 4)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 5)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 6)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 7)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 8)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(1, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, -1)), // Formation is untargeted, so targetNum is -1
    // std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 0)),
    // std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 1)),
    // std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 2)),
    // std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 3)),
    // std::make_pair(SPELL_ALLY_ACTION,std::make_pair(2, 4)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 0)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 1)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 2)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 3)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 4)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 5)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 6)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 7)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 8)),
    // std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(2, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, -1)), // For untargeted Gray spells
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 0)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 1)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 2)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 3)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(3, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 0)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 1)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 2)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 3)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 5)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 6)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 7)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 8)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(3, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, -1)), // For untargeted Red spells
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 0)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 1)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 2)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 3)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(4, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 0)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 1)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 2)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 3)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 5)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 6)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 7)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 8)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(4, 9)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, -1)), // For untargeted Blue spells
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 0)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 1)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 2)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 3)),
    std::make_pair(SPELL_ALLY_ACTION,std::make_pair(5, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 0)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 1)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 2)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 3)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 4)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 5)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 6)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 7)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 8)),
    std::make_pair(SPELL_ENEMY_ACTION,std::make_pair(5, 9)),
    std::make_pair(REROLL_ACTION,std::make_pair(0,0)), // For skipping rerolls, since AI is forced to fully roll down
    std::make_pair(REROLL_ACTION,std::make_pair(1,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(2,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(3,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(4,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(5,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(6,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(7,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(8,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(9,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(10,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(11,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(12,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(13,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(14,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(15,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(16,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(17,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(18,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(19,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(20,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(21,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(22,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(23,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(24,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(25,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(26,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(27,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(28,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(29,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(30,0)),
    std::make_pair(REROLL_ACTION,std::make_pair(31,0)),
    std::make_pair(END_TURN_ACTION,std::make_pair(0, 0)),
    std::make_pair(CONTINUE_ACTION,std::make_pair(0, 0)),
};